[features]
seeds = true
skip-lint = false

[programs.localnet]
tic_tac_toe = "BiizM1jU9UJcUZUJaeCV33QByTYjekSBQ5Q5MdoH1R1Z"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/caffeineduck/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
