[features]
seeds = true
skip-lint = false

[programs.localnet]
tic_tac_toe = "HTjZ3QP4pN6PEVmuSvZgBDYEnsr57srsAzGjB1L8AkYN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/caffeineduck/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
